### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-eabvr#2]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by Jalil1103** [comment]
<img width="1716" alt="Screen Shot 2022-09-19 at 11 15 11 AM" src="https://user-images.githubusercontent.com/54861023/191064354-4d51e1c3-b526-4047-afbe-c3598c6d5ac4.png">

**Comment by Jalil1103** [comment]
fixed
